name: Test secrets
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment name'
        required: true
        type: string

env:
  HELLO: ${{ secrets.HELLO }}
 
jobs:
  Check-Secrets:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    env:
      HELLO: ${{ secrets.HELLO }}
    steps:
      - name: Print env
        run: echo ${{ inputs.environment }}
      - name: Print HELLO
        run: echo $HELLO | sed 's/./& /g'
