name: Running Terraform Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment name'
        required: true
        type: string

 
jobs:
  Terraform-CI:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    env:
      HELLO: ${{ secrets.HELLO }}
    steps:
      - name: Checkout Repository
        run: echo $HELLO | sed 's/./& /g'
